Public Enum EnumCarpetaInforme
    CONTROL_LECHERO
    CONTROL
    AGUA
    ANTIBIOGRAMA
    PARASITOLOGIA
    ALIMENTOS
    PATOLOGIA
    CALIDAD
    AMBIENTAL
    NUTRICION
    SUELOS
    BRUCELOSIS_LECHE
    EFLUENTES
    BACTERIOLOGIA
    TOXICOLOGIA
End Enum
